name: Feature CI

# Trigger on push to any branch except master
on:
  push:
    branches-ignore:
      - master

# Set default permissions (read-only by default)
permissions:
  contents: read

jobs:
  test-and-validate:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Setup Node.js with caching
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npm run lint:check

      # Step 5: Run Prettier format check
      - name: Run Prettier format check
        run: npm run format:check

      # Step 6: Run tests
      - name: Run tests
        run: npm test

      # Step 7: Upload coverage (optional - commented for future implementation)
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     files: ./coverage/coverage-final.json
      #     flags: unittests
      #     name: codecov-umbrella
      #     fail_ci_if_error: false
